/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Service.KhoiLuong_SerVice;
import Service.NhaCungCap_SerVice;
import Service.SanPham_SerVice;
import Service.ThuongHieu_SerVice;
import Service.XuatXu_SerVice;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhoiLuong;
import model.ThuongHieu;
import model.XuatXu;

/**
 *
 * @author ADMIN
 */
public class SanPham extends javax.swing.JPanel {

    /**
     * Creates new form SanPham
     */
    DefaultComboBoxModel<ThuongHieu> ModelComboTH = new DefaultComboBoxModel<>();
    private final ThuongHieu_SerVice THservice = new ThuongHieu_SerVice();
    DefaultComboBoxModel<XuatXu> ModelComboXX = new DefaultComboBoxModel<>();
    private final XuatXu_SerVice XXservice = new XuatXu_SerVice();
    DefaultComboBoxModel<KhoiLuong> ModelComboKL = new DefaultComboBoxModel<>();
    private final KhoiLuong_SerVice KLservice = new KhoiLuong_SerVice();
   
//    private final NhaCungCap_SerVice nccservice = new NhaCungCap_SerVice();
    
    DefaultTableModel modelSP = new DefaultTableModel();
    private final SanPham_SerVice SPservice = new SanPham_SerVice();

    public SanPham() {
        initComponents();

        cboKhoiLuong.setModel((DefaultComboBoxModel) ModelComboKL);
        ArrayList<KhoiLuong> listKL = KLservice.getAllKhoiLuong();
        for (KhoiLuong kl : listKL) {
            ModelComboKL.addElement(kl);
        }

        cboThuonghieu.setModel((DefaultComboBoxModel) ModelComboTH);
        ArrayList<ThuongHieu> listTH = THservice.getAllThuongHieu();
        for (ThuongHieu th : listTH) {
            ModelComboTH.addElement(th);
        }

        cbo_Xuatxu.setModel((DefaultComboBoxModel) ModelComboXX);
        ArrayList<XuatXu> listXX = XXservice.getAllXuatXu();
        for (XuatXu xx : listXX) {
            ModelComboXX.addElement(xx);
        }

        modelSP = (DefaultTableModel) tbl_ChiTietSanPham.getModel();

        loadTable();
        if (tbl_ChiTietSanPham.getRowCount() > 0) {
            tbl_ChiTietSanPham.setRowSelectionInterval(0, 0);
            ShowDetail();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSP = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        txt_SoLuong = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        cbo_Xuatxu = new javax.swing.JComboBox<>();
        cboThuonghieu = new javax.swing.JComboBox<>();
        cboKhoiLuong = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtNCC = new javax.swing.JTextField();
        tbnThem = new javax.swing.JButton();
        tbnSua = new javax.swing.JButton();
        tbnXoa = new javax.swing.JButton();
        tbnThemMoi = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ChiTietSanPham = new javax.swing.JTable();
        txtTimkiemTenSP = new javax.swing.JTextField();
        btn_Tim = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpSP.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(252, 223, 223));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quản lý sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã SP:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Số lượng:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Giá:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tên SP:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Xuất xứ:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Thương hiệu:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Khối lượng :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Nhà cung cấp:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboKhoiLuong, 0, 87, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbo_Xuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_SoLuong)
                            .addComponent(cboThuonghieu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNCC)))
                .addGap(0, 56, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cboKhoiLuong, cboThuonghieu, cbo_Xuatxu, txtGia, txtMaSP, txtTenSP, txt_SoLuong});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cboThuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(cbo_Xuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(cboKhoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbo_Xuatxu, txtMaSP, txtTenSP});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cboKhoiLuong, cboThuonghieu, txtGia, txt_SoLuong});

        tbnThem.setBackground(new java.awt.Color(252, 223, 223));
        tbnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-add-30.png"))); // NOI18N
        tbnThem.setText("   Thêm");
        tbnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnThemActionPerformed(evt);
            }
        });

        tbnSua.setBackground(new java.awt.Color(252, 223, 223));
        tbnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-update-32.png"))); // NOI18N
        tbnSua.setText("  Sửa");
        tbnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnSuaActionPerformed(evt);
            }
        });

        tbnXoa.setBackground(new java.awt.Color(252, 223, 223));
        tbnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-delete-30.png"))); // NOI18N
        tbnXoa.setText("Xóa");
        tbnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnXoaActionPerformed(evt);
            }
        });

        tbnThemMoi.setBackground(new java.awt.Color(252, 223, 223));
        tbnThemMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-eraser-30.png"))); // NOI18N
        tbnThemMoi.setText("Mới");
        tbnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnThemMoiActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_ChiTietSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng", "Giá", "Nhà cung cấp", "Thương hiệu", "Xuất xứ", "Khối lượng", "Trạng thái"
            }
        ));
        tbl_ChiTietSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ChiTietSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ChiTietSanPham);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        btn_Tim.setBackground(new java.awt.Color(252, 223, 223));
        btn_Tim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-search-26.png"))); // NOI18N
        btn_Tim.setText("Tìm kiếm");
        btn_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtTimkiemTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Tim))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbnThem)
                                    .addComponent(tbnXoa))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbnThemMoi)
                                    .addComponent(tbnSua))))))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tbnSua, tbnThem, tbnThemMoi, tbnXoa});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbnThem))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbnThemMoi)
                            .addComponent(tbnXoa))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Tim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTimkiemTenSP)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tbnSua, tbnThem, tbnThemMoi, tbnXoa});

        jTabbedPane1.addTab("Sản Phẩm", jPanel2);

        javax.swing.GroupLayout jpSPLayout = new javax.swing.GroupLayout(jpSP);
        jpSP.setLayout(jpSPLayout);
        jpSPLayout.setHorizontalGroup(
            jpSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jpSPLayout.setVerticalGroup(
            jpSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        add(jpSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_ChiTietSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ChiTietSanPhamMouseClicked
        // TODO add your handling code here:
        try {
            ShowDetail();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi Click Form " + ERROR);
        }
    }//GEN-LAST:event_tbl_ChiTietSanPhamMouseClicked

    private void tbnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnThemMoiActionPerformed
        // TODO add your handling code here:
        clearForm();
        loadTable();

    }//GEN-LAST:event_tbnThemMoiActionPerformed

    private void tbnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnXoaActionPerformed
        // TODO add your handling code here:
        try {
            int chon = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa?");
            if (chon != JOptionPane.YES_OPTION) {
                return;
            }
            String MaSP = txtMaSP.getText();
            if (SPservice.XoaSanPham(MaSP) != null) {
                JOptionPane.showMessageDialog(this, "xóa thành công");
                loadTable();
                if (tbl_ChiTietSanPham.getRowCount() > 0) {
                    tbl_ChiTietSanPham.setRowSelectionInterval(0, 0);
                    ShowDetail();
                } else {
                    clearForm();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không xóa được dòng nào");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi xóa");
        }
    }//GEN-LAST:event_tbnXoaActionPerformed

    private void tbnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnSuaActionPerformed
        // TODO add your handling code here:
        try {
            //check form
            if (txtMaSP.getText().equalsIgnoreCase("")
                    || txtTenSP.getText().equalsIgnoreCase("")
                    || txtGia.getText().equalsIgnoreCase("")
                    || txt_SoLuong.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
                return;
            }

            //check giá, sô lượng là số , và lớn hơn 0
            try {
                double gia = Double.parseDouble(txtGia.getText());
                int soLuong = Integer.parseInt(txt_SoLuong.getText());
                if (gia < 0) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập lại giá tiền");
                    return;
                }
                if (soLuong < 0) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập lại số lượng san phẩm");
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số cho giá tiền hoặc số lượng ");
                return;
            }

            //Lấy dữ liệu trên form
            model.SanPham sp = getSanPhamFromInput();
            if (SPservice.UpdateSanPham(sp) != null) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                loadTable();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi Sửa");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi Sửa");
        }
    }//GEN-LAST:event_tbnSuaActionPerformed

    private void tbnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnThemActionPerformed
        // TODO add your handling code here:
        try {
            //check form
            if (txtMaSP.getText().equalsIgnoreCase("")
                    || txtTenSP.getText().equalsIgnoreCase("")
                    || txtGia.getText().equalsIgnoreCase("")
                    || txt_SoLuong.getText().equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
                return;
            }
            if (checkTrungMaSP(txtMaSP.getText())) {
                JOptionPane.showMessageDialog(this, "Mã SP đã có rồi, không thêm được");
                return;
            }
            //check giá, sô lượng là số , và lớn hơn 0
            try {
                double gia = Double.parseDouble(txtGia.getText());
                int soLuong = Integer.parseInt(txt_SoLuong.getText());
                if (gia < 0) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập lại giá tiền");
                    return;
                }
                if (soLuong < 0) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập lại số lượng san phẩm");
                    return;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số cho giá tiền hoặc số lượng ");
                return;
            }

            //Lấy dữ liệu trên form
            model.SanPham sp = getSanPhamFromInput();
            if (SPservice.addSanPham(sp) != null) {
                JOptionPane.showMessageDialog(this, "thêm thành công");
                loadTable();
            } else {
                JOptionPane.showMessageDialog(this, "Không thêm được dòng nào");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi thêm");
        }
    }//GEN-LAST:event_tbnThemActionPerformed

    private void btn_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimActionPerformed
        // TODO add your handling code here:
        String Ten = txtTimkiemTenSP.getText();
        Ten = "%" + Ten + "%";
        if (SPservice.timkiemSp(Ten) != null) {
            this.loadTableTimKiem(SPservice.timkiemSp(Ten));
            if (tbl_ChiTietSanPham.getRowCount() > 0 ) {
            tbl_ChiTietSanPham.setRowSelectionInterval(0, 0);
            ShowDetail();
        }
        } else {
            JOptionPane.showMessageDialog(this, "Không thấy ");
            
        }
    }//GEN-LAST:event_btn_TimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Tim;
    private javax.swing.JComboBox<String> cboKhoiLuong;
    private javax.swing.JComboBox<String> cboThuonghieu;
    private javax.swing.JComboBox<String> cbo_Xuatxu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpSP;
    private javax.swing.JTable tbl_ChiTietSanPham;
    private javax.swing.JButton tbnSua;
    private javax.swing.JButton tbnThem;
    private javax.swing.JButton tbnThemMoi;
    private javax.swing.JButton tbnXoa;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNCC;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimkiemTenSP;
    private javax.swing.JTextField txt_SoLuong;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        ArrayList<model.SanPham> list = SPservice.GetAllSanPham();

        modelSP.setRowCount(0);
        for (model.SanPham sp : list) {
            modelSP.addRow(new Object[]{
                sp.getMaSP(),
                sp.getTenSP(),
                sp.getSoLuong(),
                sp.getGia(),
                sp.getMaccc(),
                sp.getThuonghieu(),
                sp.getXuatxu(),
                sp.getKhoiluong(),
                sp.getTrangThai()
            });
        }
    }

    private void loadTableTimKiem(List<model.SanPham> listTimSP) {

        modelSP.setRowCount(0);
        for (model.SanPham sp : listTimSP) {
            modelSP.addRow(new Object[]{
                sp.getMaSP(),
                sp.getTenSP(),
                sp.getSoLuong(),
                sp.getGia(),
                sp.getMaccc(),
                sp.getThuonghieu(),
                sp.getXuatxu(),
                sp.getKhoiluong(),
                sp.getTrangThai()
            });
        }

    }

    private void ShowDetail() {
        int index = tbl_ChiTietSanPham.getSelectedRow();

        txtMaSP.setText(tbl_ChiTietSanPham.getValueAt(index, 0).toString());

        txtTenSP.setText(tbl_ChiTietSanPham.getValueAt(index, 1).toString());

        txt_SoLuong.setText(tbl_ChiTietSanPham.getValueAt(index, 2).toString());

        txtGia.setText(tbl_ChiTietSanPham.getValueAt(index, 3).toString());
        
        txtNCC.setText(tbl_ChiTietSanPham.getValueAt(index, 4).toString());

        ThuongHieu th = (ThuongHieu) tbl_ChiTietSanPham.getValueAt(index, 5);
        ModelComboTH.setSelectedItem(th);

        XuatXu xx = (XuatXu) tbl_ChiTietSanPham.getValueAt(index, 6);
        ModelComboXX.setSelectedItem(xx);

        KhoiLuong kl = (KhoiLuong) tbl_ChiTietSanPham.getValueAt(index, 7);
        ModelComboKL.setSelectedItem(kl);

    }

    private boolean checkTrungMaSP(String MaSP) {
        for (int i = 0; i < tbl_ChiTietSanPham.getRowCount() - 1; i++) {
            if (tbl_ChiTietSanPham.getValueAt(i, 0).toString().equalsIgnoreCase(MaSP)) {
                return true;
            }
        }
        return false;
    }

    private model.SanPham getSanPhamFromInput() {

        model.SanPham sp = new model.SanPham();
        sp.setMaSP(txtMaSP.getText());
        sp.setTenSP(txtTenSP.getText());
        sp.setSoLuong(Integer.parseInt(txt_SoLuong.getText()));
        sp.setGia(Double.valueOf(txtGia.getText()));
        sp.setMaccc(txtNCC.getText());
        sp.setThuonghieu((ThuongHieu) ModelComboTH.getSelectedItem());
        sp.setXuatxu((XuatXu) ModelComboXX.getSelectedItem());
        sp.setKhoiluong((KhoiLuong) ModelComboKL.getSelectedItem());

        return sp;

    }

    private void clearForm() {
        txtMaSP.setText("");
        txtGia.setText("");
        txtTenSP.setText("");
        txt_SoLuong.setText("");
        cboThuonghieu.setSelectedItem(0);
        cboKhoiLuong.setSelectedItem(0);
        cbo_Xuatxu.setSelectedItem(0);

    }
}
